/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-21 01:26:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freepostwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/smhrd/Desktop/김정훈/Web(Server)/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/project2_h5/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1651644703037L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <script src = \"jquery-3.6.0.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/freepostwrite.css\">\r\n");
      out.write("    <title>stickcode_summernote</title>\r\n");
      out.write("    <!-- include libraries(jQuery, bootstrap) -->\r\n");
      out.write("    <link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\r\n");
      out.write("    <script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- include summernote css/js-->\r\n");
      out.write("    <link href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- nav -->\r\n");
      out.write("    <div class = \"nav\">\r\n");
      out.write("        <div class = \"logo\" >\r\n");
      out.write("            <a href =\"main.jsp\">바나다</a>\r\n");
      out.write("        </div>\r\n");
      out.write("   <div class =\"nav_but\" style =\"display: flex; justify-content: space-between;\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("      \r\n");
      out.write("		</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"title-section\">\r\n");
      out.write("        <p style=\"font-family: ibm; font-size: 60px; padding-bottom:20px;  border-bottom: 1px solid #eaeaea;\">게시판 작성</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <form id=\"articleForm\" role=\"form\" action=\"\" method=\"\">\r\n");
      out.write("        <br style=\"clear: both; margin:auto;\">\r\n");
      out.write("        <div class=\"form-main\" style=\"margin:auto;\">        \r\n");
      out.write("        	<section style=\"text-align: center; margin-bottom: 20px;\">\r\n");
      out.write("        		<div class=\"form-title\">\r\n");
      out.write("        		<input type=\"text\" name=\"formname\" placeholder=\"제목을 입력하세요\" size=70 >\r\n");
      out.write("        		</div>  \r\n");
      out.write("    		</section>\r\n");
      out.write("        	<textarea name=\"BOARD_CONTENT\" id=\"board_content\" ></textarea>       	\r\n");
      out.write("        	<div style=\"display:flex; margin:auto; width:700px;\">\r\n");
      out.write("                <div style=\" width: 150px; height: 100px; margin:auto;\">\r\n");
      out.write("                    <span style=\"font-family:ibm\">파일 이름 :</span>\r\n");
      out.write("                    <span id=\"filename_id\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\" width: 300px; height: 100px; margin:auto; display:flex;\">\r\n");
      out.write("                    <span style=\"font-family:ibm\">사진 확인 : </span>\r\n");
      out.write("                    <img class=\"editor-contents\" id=\"image\" style=\"width: 150px; height: 150px; margin-left:10px;\" src=\"./upload/1.jpg\"> \r\n");
      out.write("                </div>\r\n");
      out.write("        		<input type=\"button\" id=\"submit\" name=\"submit\"  class=\"pull-right\" value=\"등록\" \r\n");
      out.write("                style=\"margin:0 auto\" onclick=\"alert('작성완료!'); location.href='post.jsp'\"/>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("        \r\n");
      out.write("      <div class=\"editor-contents\"></div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <script >\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("        $('#summernote').summernote();\r\n");
      out.write("       });\r\n");
      out.write("   </script>\r\n");
      out.write("       \r\n");
      out.write("  <script>\r\n");
      out.write("  \r\n");
      out.write("   function sendFile(file, el) {\r\n");
      out.write("      console.log(file);\r\n");
      out.write("       console.log(el);\r\n");
      out.write(" \r\n");
      out.write("       \r\n");
      out.write("       var form_data = new FormData();\r\n");
      out.write("       form_data.append('file', file);\r\n");
      out.write("       \r\n");
      out.write("       $.ajax({\r\n");
      out.write("          data : form_data,\r\n");
      out.write("          type : \"post\",\r\n");
      out.write("          url : 'img',\r\n");
      out.write("          cache : false,\r\n");
      out.write("          contentType : false,\r\n");
      out.write("          enctype : \"multipart/form-data\",\r\n");
      out.write("          processData : false,\r\n");
      out.write("          success : function(img_path) {\r\n");
      out.write("             \r\n");
      out.write("             console.log(\"path : \"+img_path);\r\n");
      out.write("             \r\n");
      out.write("             let img_name = file.name;\r\n");
      out.write("             console.log(\"name : \"+img_name);\r\n");
      out.write("             let test = \"image\\\\\"+img_name;\r\n");
      out.write("               $(\"#filename_id\").html(img_name);\r\n");
      out.write("             console.log(test);\r\n");
      out.write("             \r\n");
      out.write("             setTimeout(() => $(\"#image\").attr(\"src\",test), 5000);\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("          },\r\n");
      out.write("          error:function(){\r\n");
      out.write("             alert(\"실패\");\r\n");
      out.write("          }\r\n");
      out.write("       }); \r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("   $('#summernote').summernote(\r\n");
      out.write("           {\r\n");
      out.write("              callbacks : {\r\n");
      out.write("                 onImageUpload : function(files) {\r\n");
      out.write("                    //        ，   formData  ，     ...      IE    \r\n");
      out.write("                    var formData = new FormData();\r\n");
      out.write("                    formData.append('file', files[0]);\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                       url : 'img',//        \r\n");
      out.write("                       type : 'POST',\r\n");
      out.write("                       data : formData,\r\n");
      out.write("                       processData : false,\r\n");
      out.write("                       contentType : false,\r\n");
      out.write("                       success : function(data) {\r\n");
      out.write("                          $('#summernote').summernote(\r\n");
      out.write("                                'insertImage', data, 'img');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                 }\r\n");
      out.write("              }\r\n");
      out.write("           });\r\n");
      out.write("\r\n");
      out.write("     $(function() {\r\n");
      out.write("        $('#board_content').summernote({\r\n");
      out.write("           placeholder : '최대 500자 작성 가능합니다.',\r\n");
      out.write("           height : 300,\r\n");
      out.write("           width : 700,\r\n");
      out.write("           lang : 'ko-KR',\r\n");
      out.write("           callbacks : {\r\n");
      out.write("              onImageUpload : function(files, editor, welEditable) {\r\n");
      out.write("                 for (var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("                    sendFile(files[i], this);\r\n");
      out.write("                 }\r\n");
      out.write("              }\r\n");
      out.write("           }\r\n");
      out.write("        });\r\n");
      out.write("     });\r\n");
      out.write("     $('#summernote')\r\n");
      out.write("           .summernote(\r\n");
      out.write("                 {\r\n");
      out.write("                	width: 100,\r\n");
      out.write("                    height : 300, // 에디터 높이\r\n");
      out.write("                    minHeight : null, // 최소 높이\r\n");
      out.write("                    maxHeight : null, // 최대 높이\r\n");
      out.write("                    focus : true, // 에디터 로딩후 포커스를 맞출지 여부\r\n");
      out.write("                    lang : \"ko-KR\", // 한글 설정\r\n");
      out.write("                    placeholder : '최대 2048자까지 쓸 수 있습니다', //placeholder 설정\r\n");
      out.write("                    callbacks : { //여기 부분이 이미지를 첨부하는 부분\r\n");
      out.write("                       onImageUpload : function(files) {\r\n");
      out.write("                          uploadSummernoteImageFile(files[0],\r\n");
      out.write("                                this);\r\n");
      out.write("                       },\r\n");
      out.write("                       onPaste : function(e) {\r\n");
      out.write("                          var clipboardData = e.originalEvent.clipboardData;\r\n");
      out.write("                          if (clipboardData\r\n");
      out.write("                                && clipboardData.items\r\n");
      out.write("                                && clipboardData.items.length) {\r\n");
      out.write("                             var item = clipboardData.items[0];\r\n");
      out.write("                             if (item.kind === 'file'\r\n");
      out.write("                                   && item.type\r\n");
      out.write("                                         .indexOf('image/') !== -1) {\r\n");
      out.write("                                e.preventDefault();\r\n");
      out.write("                             }\r\n");
      out.write("                          }\r\n");
      out.write("                       }\r\n");
      out.write("                    }\r\n");
      out.write("                 });\r\n");
      out.write("\r\n");
      out.write("     /**\r\n");
      out.write("      * 이미지 파일 업로드\r\n");
      out.write("      */\r\n");
      out.write("     function uploadSummernoteImageFile(file, editor) {\r\n");
      out.write("        data = new FormData();\r\n");
      out.write("        data.append(\"file\", file);\r\n");
      out.write("        $.ajax({\r\n");
      out.write("           data : data,\r\n");
      out.write("           type : \"POST\",\r\n");
      out.write("           url : \"/uploadSummernoteImageFile\",\r\n");
      out.write("           contentType : false,\r\n");
      out.write("           processData : false,\r\n");
      out.write("           success : function(data) {\r\n");
      out.write("              //항상 업로드된 파일의 url이 있어야 한다.\r\n");
      out.write("              $(editor).summernote('insertImage', data.url);\r\n");
      out.write("           }\r\n");
      out.write("        });\r\n");
      out.write("     }\r\n");
      out.write("   \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    <footer class = \"footer\" style=\"margin-top:70px\">\r\n");
      out.write("       <ul class = \"list\">\r\n");
      out.write("           <li class = \"list-object\">\r\n");
      out.write("               <a href = \"#\">About</a>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class = \"list-object\">⋅</li>\r\n");
      out.write("           <li class = \"list-object\">\r\n");
      out.write("               <a href = \"#\">Contact</a>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class = \"list-object\">⋅</li>\r\n");
      out.write("           <li class = \"list-object\">\r\n");
      out.write("               <a href = \"#\">Terms of Use</a>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class = \"list-object\">⋅</li>\r\n");
      out.write("           <li class = \"list-object\">\r\n");
      out.write("               <a href = \"#\">Privacy Policy</a>\r\n");
      out.write("           </li>\r\n");
      out.write("       </ul>\r\n");
      out.write("       <br>\r\n");
      out.write("       <p>© Your Website 2022. Made by H5</p>\r\n");
      out.write("   </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("             \r\n");
          out.write("               ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /freepostwrite.jsp(28,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<a href =\"object.jsp\">소분해요</a>\r\n");
          out.write("				<a href =\"peoplecategory.jsp\">재능나눔</a>\r\n");
          out.write("				<a href =\"post.jsp\">자유게시판</a>\r\n");
          out.write("                <a href=\"login.jsp\">로그인</a>\r\n");
          out.write("                <a href=\"join.jsp\" >회원가입</a>\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<a href =\"object.jsp\">소분해요</a>\r\n");
          out.write("				<a href =\"peoplecategory.jsp\">재능나눔</a>\r\n");
          out.write("				<a href =\"post.jsp\">자유게시판</a>\r\n");
          out.write("				<a href =\"LogoutCon\" style =\"margin-right:200px\">로그아웃</a>\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
