/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-25 00:19:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class game_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html lang=\"en\"><head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  \r\n");
      out.write("<link rel=\"apple-touch-icon\" type=\"image/png\" href=\"https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-title\" content=\"CodePen\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"mask-icon\" type=\"image/x-icon\" href=\"https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg\" color=\"#111\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <title>CodePen - 돌려 돌려 돌림판</title>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"https://cpwebassets.codepen.io/assets/fullpage/fullpage-1580f96ce81ff0a427cf57dda2748ce646c38efc201ae5942a29958cffa6856d.css\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<link rel=\"apple-touch-icon\" type=\"image/png\" href=\"https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-title\" content=\"CodePen\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"mask-icon\" type=\"image/x-icon\" href=\"https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg\" color=\"#111\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <title>CodePen - 돌려 돌려 돌림판</title>\r\n");
      out.write("  <script>\r\n");
      out.write("  if (document.location.search.match(/type=embed/gi)) {\r\n");
      out.write("    window.parent.postMessage(\"resize\", \"*\");\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    html { font-size: 15px; }\r\n");
      out.write("    html, body { margin: 0; padding: 0; min-height: 100%; }\r\n");
      out.write("    body { height:100%; display: flex; flex-direction: column; \r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div id=\"result-iframe-wrap\" role=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <iframe id=\"result\" srcdoc=\"\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=&quot;en&quot; >\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=&quot;UTF-8&quot;>\r\n");
      out.write("  \r\n");
      out.write("<link rel=&quot;apple-touch-icon&quot; type=&quot;image/png&quot; href=&quot;https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png&quot; />\r\n");
      out.write("<meta name=&quot;apple-mobile-web-app-title&quot; content=&quot;CodePen&quot;>\r\n");
      out.write("\r\n");
      out.write("<link rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot; href=&quot;https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico&quot; />\r\n");
      out.write("\r\n");
      out.write("<link rel=&quot;mask-icon&quot; type=&quot;image/x-icon&quot; href=&quot;https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg&quot; color=&quot;#111&quot; />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <title>CodePen - 돌려 돌려 돌림판</title>\r\n");
      out.write("  \r\n");
      out.write("  <link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css&quot;>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("  font-family: 'jalnan';\r\n");
      out.write("  src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff');\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("  font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body, button{\r\n");
      out.write("	font-family:Arial, &quot;돋움&quot;, Dotum, &quot;굴림&quot;, Gulim, &quot;Apple SD Gothic Neo&quot;, AppleGothic, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button{border:0;margin:0;padding:0;}\r\n");
      out.write("\r\n");
      out.write(".title{margin-top:50px;text-align:center;}\r\n");
      out.write("\r\n");
      out.write(".box-roulette{position:relative;margin:50px auto;width:500px;height:500px;border:10px solid #ccc;border-radius:50%;background:#ccc;overflow:hidden;}\r\n");
      out.write(".box-roulette .markers{position:absolute;left:50%;top:0;margin-left:-25px;width:0;height:0;border:25px solid #fff;border-left-color:transparent;border-right-color:transparent;border-bottom-color:transparent;z-index:9999;}\r\n");
      out.write(".box-roulette .roulette{position:relative;width:100%;height:100%;overflow:hidden;}\r\n");
      out.write(".box-roulette .item{position:absolute;top:0;width:0;height:0;border:0 solid transparent;transform-origin:0 100%;}\r\n");
      out.write(".box-roulette .label{position:absolute;left:0;top:0;color:#fff;white-space:nowrap;transform-origin:0 0;}\r\n");
      out.write(".box-roulette .label .text{display:inline-block;font-size:20px;font-weight:bold;line-height:1;vertical-align:middle;}\r\n");
      out.write("\r\n");
      out.write("#btn-start{display:block;position:absolute;left:50%;top:50%;margin:-50px 0 0 -50px; font-family:jalnan; width:100px;height:100px;color:white; font-size:25px; font-weight:bold;background:#ffc107;border-radius:50px;z-index:9999;cursor:pointer;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("  window.console = window.console || function(t) {};\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("  <script>\r\n");
      out.write("  if (document.location.search.match(/type=embed/gi)) {\r\n");
      out.write("    window.parent.postMessage(&quot;resize&quot;, &quot;*&quot;);\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body translate=&quot;no&quot; >\r\n");
      out.write("\r\n");
      out.write("  <p class=&quot;title&quot;></p>\r\n");
      out.write("\r\n");
      out.write("<div class=&quot;box-roulette&quot;>\r\n");
      out.write("	<div class=&quot;markers&quot;></div>\r\n");
      out.write("	<button type=&quot;button&quot; id=&quot;btn-start&quot;>\r\n");
      out.write("		<h1>바나다</h1>\r\n");
      out.write("	</button>\r\n");
      out.write("	<div class=&quot;roulette&quot; id=&quot;roulette&quot;></div>\r\n");
      out.write("</div>\r\n");
      out.write("    <script src=&quot;https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-1b93190375e9ccc259df3a57c1abc0e64599724ae30d7ea4c6877eb615f89387.js&quot;></script>\r\n");
      out.write("\r\n");
      out.write("  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js'></script>\r\n");
      out.write("<script src='https://cdn.sobekrepository.org/includes/jquery-rotate/2.2/jquery-rotate.min.js'></script>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js'></script>\r\n");
      out.write("      <script id=&quot;rendered-js&quot; >\r\n");
      out.write("(function ($) {\r\n");
      out.write("  $.fn.extend({\r\n");
      out.write("\r\n");
      out.write("    roulette: function (options) {\r\n");
      out.write("\r\n");
      out.write("      var defaults = {\r\n");
      out.write("        angle: 0,\r\n");
      out.write("        angleOffset: -45,\r\n");
      out.write("        speed: 5000,\r\n");
      out.write("        easing: &quot;easeInOutElastic&quot; };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      var opt = $.extend(defaults, options);\r\n");
      out.write("\r\n");
      out.write("      return this.each(function () {\r\n");
      out.write("        var o = opt;\r\n");
      out.write("\r\n");
      out.write("        var data = [\r\n");
      out.write("        {\r\n");
      out.write("          color: '#3f297e',\r\n");
      out.write("          text: 'N분의 1' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#1d61ac',\r\n");
      out.write("          text: '한번더' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#169ed8',\r\n");
      out.write("          text: '몰빵' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#209b6c',\r\n");
      out.write("          text: '상관없음' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#60b236',\r\n");
      out.write("          text: 'N분의 1' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#efe61f',\r\n");
      out.write("          text: '한번더' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#f7a416',\r\n");
      out.write("          text: '몰빵' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#e6471d',\r\n");
      out.write("          text: '상관없음' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#dc0936',\r\n");
      out.write("          text: 'N분의 1' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#e5177b',\r\n");
      out.write("          text: '한번더' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#be107f',\r\n");
      out.write("          text: '몰빵' },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          color: '#881f7e',\r\n");
      out.write("          text: '상관없음' }];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var $wrap = $(this);\r\n");
      out.write("        var $btnStart = $wrap.find(&quot;#btn-start&quot;);\r\n");
      out.write("        var $roulette = $wrap.find(&quot;.roulette&quot;);\r\n");
      out.write("        var wrapW = $wrap.width();\r\n");
      out.write("        var angle = o.angle;\r\n");
      out.write("        var angleOffset = o.angleOffset;\r\n");
      out.write("        var speed = o.speed;\r\n");
      out.write("        var esing = o.easing;\r\n");
      out.write("        var itemSize = data.length;\r\n");
      out.write("        var itemSelector = &quot;item&quot;;\r\n");
      out.write("        var labelSelector = &quot;label&quot;;\r\n");
      out.write("        var d = 360 / itemSize;\r\n");
      out.write("        var borderTopWidth = wrapW;\r\n");
      out.write("        var borderRightWidth = tanDeg(d);\r\n");
      out.write("\r\n");
      out.write("        for (i = 1; i <= itemSize; i += 1) {if (window.CP.shouldStopExecution(0)) break;\r\n");
      out.write("          var idx = i - 1;\r\n");
      out.write("          var rt = i * d + angleOffset;\r\n");
      out.write("          var itemHTML = $('<div class=&quot;' + itemSelector + '&quot;>');\r\n");
      out.write("          var labelHTML = '';\r\n");
      out.write("          labelHTML += '<p class=&quot;' + labelSelector + '&quot;>';\r\n");
      out.write("          labelHTML += '	<span class=&quot;text&quot;>' + data[idx].text + '<\\/span>';\r\n");
      out.write("          labelHTML += '<\\/p>';\r\n");
      out.write("\r\n");
      out.write("          $roulette.append(itemHTML);\r\n");
      out.write("          $roulette.children(&quot;.&quot; + itemSelector).eq(idx).append(labelHTML);\r\n");
      out.write("          $roulette.children(&quot;.&quot; + itemSelector).eq(idx).css({\r\n");
      out.write("            &quot;left&quot;: wrapW / 2,\r\n");
      out.write("            &quot;top&quot;: -wrapW / 2,\r\n");
      out.write("            &quot;border-top-width&quot;: borderTopWidth,\r\n");
      out.write("            &quot;border-right-width&quot;: borderRightWidth,\r\n");
      out.write("            &quot;border-top-color&quot;: data[idx].color,\r\n");
      out.write("            &quot;transform&quot;: &quot;rotate(&quot; + rt + &quot;deg)&quot; });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          var textH = parseInt(2 * Math.PI * wrapW / d * .5);\r\n");
      out.write("\r\n");
      out.write("          $roulette.children(&quot;.&quot; + itemSelector).eq(idx).children(&quot;.&quot; + labelSelector).css({\r\n");
      out.write("            &quot;height&quot;: textH + 'px',\r\n");
      out.write("            &quot;line-height&quot;: textH + 'px',\r\n");
      out.write("            &quot;transform&quot;: 'translateX(' + textH * 1.3 + 'px) translateY(' + wrapW * -.3 + 'px) rotateZ(' + (90 + d * .5) + 'deg)' });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        }window.CP.exitedLoop(0);\r\n");
      out.write("\r\n");
      out.write("        function tanDeg(deg) {\r\n");
      out.write("          var rad = deg * Math.PI / 180;\r\n");
      out.write("          return wrapW / (1 / Math.tan(rad));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $btnStart.on(&quot;click&quot;, function () {\r\n");
      out.write("          rotation();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function rotation() {\r\n");
      out.write("\r\n");
      out.write("          var completeA = 360 * r(5, 10) + r(0, 360);\r\n");
      out.write("\r\n");
      out.write("          $roulette.rotate({\r\n");
      out.write("            angle: angle,\r\n");
      out.write("            animateTo: completeA,\r\n");
      out.write("            center: [&quot;50%&quot;, &quot;50%&quot;],\r\n");
      out.write("            easing: $.easing.esing,\r\n");
      out.write("            callback: function () {\r\n");
      out.write("              var currentA = $(this).getRotateAngle();\r\n");
      out.write("\r\n");
      out.write("              console.log(currentA);\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            duration: speed });\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function r(min, max) {\r\n");
      out.write("          return Math.floor(Math.random() * (max - min + 1)) + min;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("    } });\r\n");
      out.write("\r\n");
      out.write("})(jQuery);\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("\r\n");
      out.write("  $('.box-roulette').roulette();\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("//# sourceURL=pen.js\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write(" \r\n");
      out.write("\" sandbox=\"allow-downloads allow-forms allow-modals allow-pointer-lock allow-popups allow-presentation  allow-scripts allow-top-navigation-by-user-activation\" allow=\"accelerometer; camera; encrypted-media; display-capture; geolocation; gyroscope; microphone; midi; clipboard-read; clipboard-write; web-share\" allowtransparency=\"true\" allowpaymentrequest=\"true\" allowfullscreen=\"true\" class=\"result-iframe\">\r\n");
      out.write("      </iframe>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <div style=\"text-align:center;\">\r\n");
      out.write("  <button style=\"margin-bottom:40px; background:#ffc107; color:white; cursor:pointer; border-radius:40px; border:none; width:200px; padding:30px; font-size:20px; font-family:jalnan;\" type=\"button\" onclick=\"location.href='main.jsp';\">메인으로\r\n");
      out.write("  </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
