/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-26 06:48:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.smhrd.domain.UserDAO;
import com.smhrd.domain.User;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/smhrd/Desktop/김정훈/Web(Server)/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/project2_h5/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1651644703037L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.smhrd.domain.UserDAO");
    _jspx_imports_classes.add("com.smhrd.domain.User");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String MT = (String)request.getAttribute("MT");
String nick = (String)request.getAttribute("nick");

      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("        <meta name=\"description\" content=\"\" />\n");
      out.write("        <meta name=\"author\" content=\"\" />\n");
      out.write("        <title>Landing Page - Start Bootstrap Theme</title>\n");
      out.write("        <!-- Favicon-->\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\n");
      out.write("        <!-- Bootstrap icons-->\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- Google fonts-->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Single+Day&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("        div, ul, li {-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;padding:0;margin:0}\n");
      out.write("a {text-decoration:none;}\n");
      out.write("\n");
      out.write(".quickmenu {position:absolute;width:300px;top:50%;margin-top:-50px;right:10px;background:#fff;}\n");
      out.write(".quickmenu ul {position:relative;float:left;width:100%;display:inline-block;*display:inline;border:1px solid #ddd;}\n");
      out.write(".quickmenu ul li {float:left;width:100%;border-bottom:1px solid #ddd;text-align:center;display:inline-block;*display:inline;}\n");
      out.write(".quickmenu ul li a {position:relative;float:left;width:100%;height:30px;line-height:30px;text-align:center;color:#999;font-size:9.5pt;}\n");
      out.write(".quickmenu ul li a:hover {color:#000;}\n");
      out.write(".quickmenu ul li:last-child {border-bottom:0;}\n");
      out.write("\n");
      out.write(".content {position:relative;min-height:1000px;}\n");
      out.write("        </style>\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("        <link href=\"assets/styles.css\" rel=\"stylesheet\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!--상단바-->\n");
      out.write("        <nav class=\"navbar navbar-light bg-light static-top\" style = \"border-bottom: 1px solid #eaeaea;\">\n");
      out.write("            <div class=\"left\">\n");
      out.write("                <a class=\"navbar-brand\" style = \"font-family : jalnan\" href=\"main.jsp\">바나다</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav_but\" style = \"padding-top:40px;\">\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </nav>\n");
      out.write("        <!-- 중앙 검색창-->\n");
      out.write("        <header class=\"masthead\" style = \"background-color:#FAFAFA;\">\n");
      out.write("            <div class=\"container position-relative\">\n");
      out.write("                <div class=\"row justify-content-center\">\n");
      out.write("                    <div class=\"col-xl-6\">\n");
      out.write("                        <div class=\"text-center\">\n");
      out.write("                            <!-- Page heading-->\n");
      out.write("                            <h1 class=\"mb-5 \" style = \"font-family: 'ibm'; font-weight: 100px;\">\n");
      out.write("                                <span color=\"#ffc107\">바나다에</span>\n");
      out.write("                                <br>\n");
      out.write("                                <span>반하다</span>\n");
      out.write("                            </h1>\n");
      out.write("                            <!-- Signup form-->\n");
      out.write("                            <!-- * * * * * * * * * * * * * * *-->\n");
      out.write("                            <!-- * * SB Forms Contact Form * *-->\n");
      out.write("                            <!-- * * * * * * * * * * * * * * *-->\n");
      out.write("                            <!-- This form is pre-integrated with SB Forms.-->\n");
      out.write("                            <!-- To make this form functional, sign up at-->\n");
      out.write("                            <!-- https://startbootstrap.com/solution/contact-forms-->\n");
      out.write("                            <!-- to get an API token!-->\n");
      out.write("                            <form class=\"form-subscribe\" id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\n");
      out.write("                                <!-- Email address input-->\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col\">\n");
      out.write("                                        <input class=\"form-control form-control-lg\" id =\"text-bar\" type=\"text\" placeholder=\"찾는게 있으신가요?\" />\n");
      out.write("                                        \n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-auto font-paybooc btn-center\"><button class=\"btn btn-primary \" id=\"submitButton\" type=\"submit\">검색</button></div>\n");
      out.write("                                </div>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <!--중앙 3분할 설명창-->\n");
      out.write("        <section class=\"features-icons bg-light-yellow text-center\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row font-paybooc\">\n");
      out.write("                    <div class=\"col-lg-4 \" >\n");
      out.write("                        <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\" style=\"align-items:center;\">\n");
      out.write("                            <div class=\"features-icons-icon d-flex\" \">\n");
      out.write("                                <img style=\"margin-left: 100px; margin-bottom:10px; border-radius: 30%;\" src=\"assets/main_img/free-icon-fruits-3524528.png\" >\n");
      out.write("                            </div>\n");
      out.write("                            <a href=\"object.jsp\" class=\"mini-category\">소분해요</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\">\n");
      out.write("                            <div class=\"features-icons-icon d-flex\">\n");
      out.write("                                <img style=\"margin-left: 100px; margin-bottom:10px; border-radius: 30%;\" src=\"assets/main_img/party.png\" >\n");
      out.write("                            </div>\n");
      out.write("                            <a href=\"peoplecategory.jsp\" class=\"mini-category\"s>취미공유</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <div class=\"features-icons-item mx-auto mb-0 mb-lg-3\">\n");
      out.write("                            <div class=\"features-icons-icon d-flex\">\n");
      out.write("                                <img style=\"margin-left: 115px; margin-bottom:10px;\" src=\"assets/main_img/resume.png\" >\n");
      out.write("                            </div>\n");
      out.write("                            <a href=\"reviewpost.jsp\" class=\"mini-category\">나눔후기</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Image Showcases-->\n");
      out.write("        <section class=\"showcase\">\n");
      out.write("            <div class=\"container-fluid p-0\" style = \"background-color: #FAFAFA\">\n");
      out.write("                <div class=\"row g-0\">\n");
      out.write("                    <div class=\"col-lg-6 order-lg-2 text-white showcase-img\" style=\"background-image: url('assets/main_img/bg-showcase-1.png')\"></div>\n");
      out.write("                    <div class=\"col-lg-6 order-lg-1 my-auto showcase-text\">\n");
      out.write("                        <h2 class =\"font-paybooc\"> 소분 할 사람 ?</h2>\n");
      out.write("                        <p class=\"lead mb-0\" style=\"margin-top:20px\";>물건이 남아서 힘드셨다구요?</p>\n");
      out.write("                        <p class=\"lead mb-0\">바나다에서 해결하세요.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row g-0\" >\n");
      out.write("                    <div class=\"col-lg-6 text-white showcase-img\" style=\"background-image: url('assets/main_img/bg-showcase-2.jpg')\"></div>\n");
      out.write("                    <div class=\"col-lg-6 my-auto showcase-text\">\n");
      out.write("                        <h2 class =\"font-paybooc\">취미 공유는 어때요 ?</h2>\n");
      out.write("                        <p class=\"lead mb-0\" style=\"margin-top:20px\";>혼자서는 심심하겠지만</p>\n");
      out.write("                        <p class=\"lead mb-0\">둘이서 하면 즐거움도 2배 !</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row g-0\">\n");
      out.write("                    <div class=\"col-lg-6 order-lg-2 text-white showcase-img\" style=\"background-image: url('assets/main_img/bg-showcase-3.jpg')\"></div>\n");
      out.write("                    <div class=\"col-lg-6 order-lg-1 my-auto showcase-text\">\n");
      out.write("                        <h2 class =\"font-paybooc\">재능 나눔 할 사람 ?</h2>\n");
      out.write("                        <p class=\"lead mb-0\" style=\"margin-top:20px\";>능력을 숨기고 사시느라 힘드셨죠?</p>\n");
      out.write("                        <p class=\"lead mb-0\">이제 숨기지 말고 보여주세요 !</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Testimonials-->\n");
      out.write("        <section class=\"testimonials text-center bg-light\">\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("         \n");
      out.write("\n");
      out.write("         \n");
      out.write("         \n");
      out.write("        <!-- Footer-->\n");
      out.write("        <footer class=\"footer \" style=\"height:150px;\"\">\n");
      out.write("                <div class=\"container col-lg-6 h-100 text-center text-lg-start my-auto\">\n");
      out.write("                        <ul class=\"list-inline mb-2\" style=\"color:black; text-decoration:none;\">\n");
      out.write("                            <li class=\"list-inline-item\"><a href=\"#!\" style=\"color:black; text-decoration:none;\">About</a></li>\n");
      out.write("                            <li class=\"list-inline-item\">⋅</li>\n");
      out.write("                            <li class=\"list-inline-item\"><a href=\"#!\" style=\"color:black; text-decoration:none;\">Contact</a></li>\n");
      out.write("                            <li class=\"list-inline-item\">⋅</li>\n");
      out.write("                            <li class=\"list-inline-item\"><a href=\"#!\" style=\"color:black; text-decoration:none;\">Terms of Use</a></li>\n");
      out.write("                            <li class=\"list-inline-item\">⋅</li>\n");
      out.write("                            <li class=\"list-inline-item\"><a href=\"#!\" style=\"color:black; text-decoration:none;\">Privacy Policy</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                        <p class=\"text-muted small mb-4 mb-lg-0\">&copy; Your Website 2022. Made by H5</H></p>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- Bootstrap core JS-->\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <!-- Core theme JS-->\n");
      out.write("        <script src=\"js/scripts.js\"></script>\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n");
      out.write("        <!-- * *                               SB Forms JS                               * *-->\n");
      out.write("        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("                    <!-- 시계-->\n");
      out.write("   ");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("               ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("               ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /main.jsp(49,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                  <a href=\"login.jsp\">로그인</a>\n");
          out.write("                  <a href=\"join.jsp\">회원가입</a>\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("               	  <a href=\"myreview.jsp?user_nick=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.user_nick }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">받은 후기</a>\n");
          out.write("                  <a href=\"LogoutCon\">로그아웃</a>\n");
          out.write("              </div>\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("               ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("               ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /main.jsp(160,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("               <div class=\"container\">\n");
          out.write("                <h2 class=\"mb-5 font-paybooc\">좋아요 Best 3</h2>\n");
          out.write("               \n");
          out.write("\n");
          out.write("                <div class=\"row\">\n");
          out.write("                    <div class=\"col-lg-4\">\n");
          out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\n");
          out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"http://img.danawa.com/prod_img/500000/653/800/img/6800653_1.jpg?shrink=500:500&_v=20211026150548\" alt=\"...\" />\n");
          out.write("                            <h5>1위</h5>\n");
          out.write("                            <p class=\"font-weight-light mb-0\">대용량 윙봉</p>\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                    <div class=\"col-lg-4\">\n");
          out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\n");
          out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"image/world.png\" alt=\"...\" />\n");
          out.write("                            <h5>2위</h5>\n");
          out.write("                            <p class=\"font-weight-light mb-0\">세계맥주</p>\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                    <div class=\"col-lg-4\">\n");
          out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\n");
          out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"image/original.png\" alt=\"...\" />\n");
          out.write("                            <h5>3위</h5>\n");
          out.write("                            <p class=\"font-weight-light mb-0\">크리스피 도넛</p>\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                </div>\n");
          out.write("              </div>\n");
          out.write("            </section>\n");
          out.write("         \n");
          out.write("         ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            \n");
          out.write("            \n");
          out.write("         \n");
          out.write("         \n");
          out.write("         	<div class=\"container\">\n");
          out.write("                   \n");
          out.write("                   <h2 class=\"mb-5 font-paybooc\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.user_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님에게 추천드려요</h2><br><h2 class=\"mb-5 font-paybooc\">Best3</h2>\n");
          out.write("               \n");
          out.write("                <div class=\"row\">\n");
          out.write("                    <div class=\"col-lg-4\">\n");
          out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\n");
          out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"image/cola.png\" alt=\"...\" />\n");
          out.write("                            <h5>추천 1</h5>\n");
          out.write("                            <p class=\"font-weight-light mb-0\">\"콜라..같이사실분?\"</p>\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                    <div class=\"col-lg-4\">\n");
          out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\n");
          out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"image/butter.png\" alt=\"...\" />\n");
          out.write("                            <h5>추천 2</h5>\n");
          out.write("                            <p class=\"font-weight-light mb-0\">\"버터가 남았어요!\"</p>\n");
          out.write("                        </div>\n");
          out.write("                    </div> \n");
          out.write("                    <div class=\"col-lg-4\">\n");
          out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\n");
          out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"image/flower.png\" alt=\"...\" />\n");
          out.write("                            <h5>추천 3</h5>\n");
          out.write("                            <p class=\"font-weight-light mb-0\">\"꽃 같이 사실분?\"</p>\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                </div>\n");
          out.write("              </div>\n");
          out.write("            </section>\n");
          out.write("         \n");
          out.write("\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent(null);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("     ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("          ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /main.jsp(263,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("         ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("   \n");
          out.write("        <div class=\"quickmenu\" style=\"top:750px; background:white; border-radius: 25px; border:3px solid #ffc107;\"> \n");
          out.write("       			<div style=\"width: 90%;  margin: 10px auto; display: flex;\"> \n");
          out.write("       			 <button type=\"button\" onclick=\"location.href='chat.jsp';\" style=\"font-family:ibm; border-radius: 25px; border: 3px solid #ffc107; flex:1; margin: 0 5px; width:30%; box-sizing: border-box;\">\n");
          out.write("          			채팅\n");
          out.write("          		</button>   \n");
          out.write("          		<button type=\"button\" onclick=\"location.href='game.jsp';\" style=\"font-family:ibm; border-radius: 25px; border: 3px solid #ffc107;flex:1; margin:0 5px; width:30%; box-sizing: border-box;\" >\n");
          out.write("          			결제\n");
          out.write("          		</button>\n");
          out.write("          		</div>\n");
          out.write("          		");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f2, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("        <script src = \"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
          out.write("        <script type=\"text/javascript\">\n");
          out.write("\n");
          out.write("CountDownTimer('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', 'countdown');\n");
          out.write("\n");
          out.write("function CountDownTimer(dt, id) {\n");
          out.write("\n");
          out.write("    var end = new Date(dt);\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("    var _second = 1000;\n");
          out.write("\n");
          out.write("    var _minute = _second * 60;\n");
          out.write("\n");
          out.write("    var _hour = _minute * 60;\n");
          out.write("\n");
          out.write("    var _day = _hour * 24;\n");
          out.write("\n");
          out.write("    var timer;\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("    function showRemaining() {\n");
          out.write("\n");
          out.write("        var now = new Date();\n");
          out.write("\n");
          out.write("        var distance = end - now;\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("        // 시간 종료 시 뜨는 문구\n");
          out.write("\n");
          out.write("        if (distance < 0) {\n");
          out.write("\n");
          out.write("            clearInterval(timer);\n");
          out.write("\n");
          out.write("            document.getElementById(id).innerHTML = '약속 시간입니다. 약속 장소로 나가!';\n");
          out.write("\n");
          out.write("            return;\n");
          out.write("\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        var days = Math.floor(distance / _day);\n");
          out.write("\n");
          out.write("        var hours = Math.floor((distance % _day) / _hour);\n");
          out.write("\n");
          out.write("        var minutes = Math.floor((distance % _hour) / _minute);\n");
          out.write("\n");
          out.write("        var seconds = Math.floor((distance % _minute) / _second);\n");
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("        document.getElementById(id).innerHTML = days + '일 ';\n");
          out.write("\n");
          out.write("        document.getElementById(id).innerHTML += hours + '시간 ';\n");
          out.write("\n");
          out.write("        document.getElementById(id).innerHTML += minutes + '분 ';\n");
          out.write("\n");
          out.write("        document.getElementById(id).innerHTML += seconds + '초';\n");
          out.write("\n");
          out.write("    }\n");
          out.write("\n");
          out.write("    timer = setInterval(showRemaining, 1000);\n");
          out.write("\n");
          out.write("}\n");
          out.write("</script>\n");
          out.write("        \n");
          out.write("        <script>\n");
          out.write("        $(document).ready(function(){ \n");
          out.write("           var currentPosition = parseInt($(\".quickmenu\").css(\"top\")); \n");
          out.write("           $(window).scroll(function() { \n");
          out.write("               var position = $(window).scrollTop(); \n");
          out.write("               $(\".quickmenu\").stop().animate({\"top\":position+currentPosition+\"px\"},1000); \n");
          out.write("               }); \n");
          out.write("           });\n");
          out.write("        </script>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f2);
      // /main.jsp(275,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.user_nick eq nick}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <div style=\"font-family:ibm;\">약속시간</div>\n");
          out.write("		<div id=\"countdown\" style=\"font-family:ibm;\"></div>\n");
          out.write("		<div style=\"font-family:ibm\">남았습니다.</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
