/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-24 09:23:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class option_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src = \"js/jquery-3.6.0.js\"></script>\r\n");
      out.write("    <script language=\"JavaScript\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    html, body, button{\r\n");
      out.write("	font-family:Arial, \"돋움\", Dotum, \"굴림\", Gulim, \"Apple SD Gothic Neo\", AppleGothic, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button{border:0;margin:0;padding:0;}\r\n");
      out.write("\r\n");
      out.write(".title{margin-top:50px;text-align:center;}\r\n");
      out.write("\r\n");
      out.write(".box-roulette{position:relative;margin:50px auto;width:500px;height:500px;border:10px solid #ccc;border-radius:50%;background:#ccc;overflow:hidden;}\r\n");
      out.write(".box-roulette .markers{position:absolute;left:50%;top:0;margin-left:-25px;width:0;height:0;border:25px solid #fff;border-left-color:transparent;border-right-color:transparent;border-bottom-color:transparent;z-index:9999;}\r\n");
      out.write(".box-roulette .roulette{position:relative;width:100%;height:100%;overflow:hidden;}\r\n");
      out.write(".box-roulette .item{position:absolute;top:0;width:0;height:0;border:0 solid transparent;transform-origin:0 100%;}\r\n");
      out.write(".box-roulette .label{position:absolute;left:0;top:0;color:#fff;white-space:nowrap;transform-origin:0 0;}\r\n");
      out.write(".box-roulette .label .text{display:inline-block;font-size:20px;font-weight:bold;line-height:1;vertical-align:middle;}\r\n");
      out.write("\r\n");
      out.write("#btn-start{display:block;position:absolute;left:50%;top:50%;margin:-50px 0 0 -50px;width:100px;height:100px;font-weight:bold;background:#fff;border-radius:50px;z-index:9999;cursor:pointer;}</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<p class=\"title\">본의아니 행운의 여보세요?</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"box-roulette\">\r\n");
      out.write("	<div class=\"markers\"></div>\r\n");
      out.write("	<button type=\"button\" id=\"btn-start\">\r\n");
      out.write("		돌려 돌려<br>돌림판\r\n");
      out.write("	</button>\r\n");
      out.write("	<div class=\"roulette\" id=\"roulette\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("(function($) {\r\n");
      out.write("	  $.fn.extend({\r\n");
      out.write("\r\n");
      out.write("	    roulette: function(options) {\r\n");
      out.write("\r\n");
      out.write("	      var defaults = {\r\n");
      out.write("	        angle: 0,\r\n");
      out.write("	        angleOffset: -45,\r\n");
      out.write("	        speed: 5000,\r\n");
      out.write("	        easing: \"easeInOutElastic\",\r\n");
      out.write("	      };\r\n");
      out.write("\r\n");
      out.write("	      var opt = $.extend(defaults, options);\r\n");
      out.write("\r\n");
      out.write("	      return this.each(function() {\r\n");
      out.write("	        var o = opt;\r\n");
      out.write("\r\n");
      out.write("	        var data = [\r\n");
      out.write("						{\r\n");
      out.write("	            color: '#3f297e',\r\n");
      out.write("	            text: 'N분의 1'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#1d61ac',\r\n");
      out.write("	            text: '요즘것들'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#169ed8',\r\n");
      out.write("	            text: '도박'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#209b6c',\r\n");
      out.write("	            text: '젓가락'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#60b236',\r\n");
      out.write("	            text: '거북선'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#efe61f',\r\n");
      out.write("	            text: '겁'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#f7a416',\r\n");
      out.write("	            text: 'Day Day'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#e6471d',\r\n");
      out.write("	            text: '호랑나비'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#dc0936',\r\n");
      out.write("	            text: 'Okey Dokey'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#e5177b',\r\n");
      out.write("	            text: '오빠차'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#be107f',\r\n");
      out.write("	            text: 'RESPECT'\r\n");
      out.write("	          },\r\n");
      out.write("	          {\r\n");
      out.write("	            color: '#881f7e',\r\n");
      out.write("	            text: '작두'\r\n");
      out.write("	          }\r\n");
      out.write("	        ];\r\n");
      out.write("\r\n");
      out.write("	        var $wrap = $(this);\r\n");
      out.write("	        var $btnStart = $wrap.find(\"#btn-start\");\r\n");
      out.write("	        var $roulette = $wrap.find(\".roulette\");\r\n");
      out.write("	        var wrapW = $wrap.width();\r\n");
      out.write("	        var angle = o.angle;\r\n");
      out.write("	        var angleOffset = o.angleOffset;\r\n");
      out.write("	        var speed = o.speed;\r\n");
      out.write("	        var esing = o.easing;\r\n");
      out.write("	        var itemSize = data.length;\r\n");
      out.write("	        var itemSelector = \"item\";\r\n");
      out.write("	        var labelSelector = \"label\";\r\n");
      out.write("	        var d = 360 / itemSize;\r\n");
      out.write("	        var borderTopWidth = wrapW;\r\n");
      out.write("	        var borderRightWidth = tanDeg(d);\r\n");
      out.write("\r\n");
      out.write("	        for (i = 1; i <= itemSize; i += 1) {\r\n");
      out.write("	          var idx = i - 1;\r\n");
      out.write("	          var rt = i * d + angleOffset;\r\n");
      out.write("	          var itemHTML = $('<div class=\"' + itemSelector + '\">');\r\n");
      out.write("	          var labelHTML = '';\r\n");
      out.write("	              labelHTML += '<p class=\"' + labelSelector + '\">';\r\n");
      out.write("	              labelHTML += '	<span class=\"text\">' + data[idx].text + '<\\/span>';\r\n");
      out.write("	              labelHTML += '<\\/p>';\r\n");
      out.write("\r\n");
      out.write("	          $roulette.append(itemHTML);\r\n");
      out.write("	          $roulette.children(\".\" + itemSelector).eq(idx).append(labelHTML);\r\n");
      out.write("	          $roulette.children(\".\" + itemSelector).eq(idx).css({\r\n");
      out.write("	            \"left\": wrapW / 2,\r\n");
      out.write("	            \"top\": -wrapW / 2,\r\n");
      out.write("	            \"border-top-width\": borderTopWidth,\r\n");
      out.write("	            \"border-right-width\": borderRightWidth,\r\n");
      out.write("	            \"border-top-color\": data[idx].color,\r\n");
      out.write("	            \"transform\": \"rotate(\" + rt + \"deg)\"\r\n");
      out.write("	          });\r\n");
      out.write("\r\n");
      out.write("	          var textH = parseInt(((2 * Math.PI * wrapW) / d) * .5);\r\n");
      out.write("\r\n");
      out.write("	          $roulette.children(\".\" + itemSelector).eq(idx).children(\".\" + labelSelector).css({\r\n");
      out.write("	            \"height\": textH + 'px',\r\n");
      out.write("	            \"line-height\": textH + 'px',\r\n");
      out.write("	            \"transform\": 'translateX(' + (textH * 1.3) + 'px) translateY(' + (wrapW * -.3) + 'px) rotateZ(' + (90 + d * .5) + 'deg)'\r\n");
      out.write("	          });\r\n");
      out.write("\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        function tanDeg(deg) {\r\n");
      out.write("	          var rad = deg * Math.PI / 180;\r\n");
      out.write("	          return wrapW / (1 / Math.tan(rad));\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	        $btnStart.on(\"click\", function() {\r\n");
      out.write("	          rotation();\r\n");
      out.write("	        });\r\n");
      out.write("\r\n");
      out.write("	        function rotation() {\r\n");
      out.write("\r\n");
      out.write("	          var completeA = 360 * r(5, 10) + r(0, 360);\r\n");
      out.write("\r\n");
      out.write("	          $roulette.rotate({\r\n");
      out.write("	            angle: angle,\r\n");
      out.write("	            animateTo: completeA,\r\n");
      out.write("	            center: [\"50%\", \"50%\"],\r\n");
      out.write("	            easing: $.easing.esing,\r\n");
      out.write("	            callback: function() {\r\n");
      out.write("	              var currentA = $(this).getRotateAngle();\r\n");
      out.write("\r\n");
      out.write("	              console.log(currentA);\r\n");
      out.write("\r\n");
      out.write("	            },\r\n");
      out.write("	            duration: speed\r\n");
      out.write("	          });\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        function r(min, max) {\r\n");
      out.write("	          return Math.floor(Math.random() * (max - min + 1)) + min;\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	      });\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("	})(jQuery);\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("\r\n");
      out.write("	  $('.box-roulette').roulette();\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
